#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

# shellcheck disable=SC2034  # RED belongs to the shared color palette; unused here.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: deploy the Zulip publisher on this machine.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

cd "$(dirname "$0")/.."
REPO_DIR="$PWD"
CONFIG="zulip_publisher.toml"
LABEL="com.example.zulip-publisher"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"

banner "Deploy the Zulip publisher"

# ── Stage 1: Local configuration ──────────────────────────────────────────
stage "Local configuration"
say "Structure lives in $CONFIG (gitignored); secrets come from SecretSpec."
if [[ -f "$CONFIG" ]]; then
  say "$CONFIG already exists; keeping it."
else
  say "Writing $CONFIG with the confirmed defaults."
  cat > "$CONFIG" <<'TOML'
# Zulip publisher configuration (machine-local; gitignored).
# Secrets come from SecretSpec, not this file.

zulip_stream = "blog"
zulip_general_topic = "general"
publisher_bot_name = "Publisher"

prepare_policy = "faithful-en-v1"
prepare_format = "markdown"

site_repo_url = "git@github.com:you/your-site.git"
site_clone_dir = "~/andysmith-ai/andysmith.ai"
site_branch = "main"
site_posts_subdir = "src"
site_url = "https://andysmith.ai"

telegram_repo_url = "git@github.com:andysmith-ai/telegram.git"
telegram_clone_dir = "~/sm-th/telegram"
telegram_branch = "main"
telegram_posts_subdir = "posts"
telegram_username = "your_channel"

r2_endpoint = "https://REDACTED_ACCOUNT.r2.cloudflarestorage.com"
r2_bucket = "your-bucket"
image_media_host = "https://files.example.com"
image_prefix = "img"

ssh_key = "~/.ssh/id_ed25519"
git_user_name = "Andy Smith"
git_user_email = "publisher@example.com"
git_sign = true
git_signing_key = "~/.ssh/id_ed25519.pub"
allowed_signers = "~/.ssh/allowed_signers"

author_timezone_fallback = "America/Los_Angeles"
poll_interval = 60
site_ready_timeout = 300
site_ready_interval = 5
telegram_state_timeout = 300
telegram_state_interval = 5
TOML
  say "Wrote $CONFIG."
fi
if confirm "Open $CONFIG to review/edit now?"; then
  "${EDITOR:-nano}" "$CONFIG"
fi

# ── Stage 2: Secrets via SecretSpec ───────────────────────────────────────
stage "Secrets (SecretSpec)"
say "The publisher reads these from SecretSpec at run time (never from disk):"
note "  ZULIP_URL, ZULIP_API_KEY, ZULIP_API_USERNAME,"
note "  PREPARE_URL, PREPARE_TOKEN, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY"
say "PREPARE_URL/PREPARE_TOKEN are what the Cloudflare deploy printed."
step "'secretspec check' will prompt for any secret not yet stored."
pause "Press Enter to run 'secretspec check'."
secretspec check || warn "some secrets are still missing; re-run this stage later."

# ── Stage 3: Clone sanity ─────────────────────────────────────────────────
stage "Repository access"
say "The publisher pushes to the website and Telegram repos over SSH."
if ssh -o StrictHostKeyChecking=accept-new -T git@github.com 2>&1 | grep -qi 'successfully authenticated'; then
  say "GitHub SSH authentication works."
else
  warn "Could not confirm GitHub SSH auth; ensure ~/.ssh/id_ed25519 is authorized."
fi

# ── Stage 4: Dry-run smoke ────────────────────────────────────────────────
stage "Dry-run smoke"
say "A dry run reads Zulip and calls the preparation Worker but writes nothing."
if confirm "Run 'PUBLISHER_DRY_RUN=1 ... once' now?"; then
  PUBLISHER_DRY_RUN=1 nix develop "path:$REPO_DIR" -c \
    secretspec run -- python -m zulip_publisher once || \
    warn "dry run reported an error; fix config/secrets before going live."
else
  note "Skipped; you can run: nix run .#debug -- once   (also dry-runnable)."
fi

# ── Stage 5: Install the LaunchAgent ──────────────────────────────────────
stage "Install the launchd agent"
if [[ "$(uname -s)" != "Darwin" ]]; then
  warn "Not macOS; skipping LaunchAgent. Run the loop under your own supervisor:"
  note "  nix develop -c secretspec run -- python -m zulip_publisher run"
else
  say "Installs $PLIST to run the poll loop at login and keep it alive."
  if confirm "Install and load the LaunchAgent now?"; then
    mkdir -p "$HOME/Library/LaunchAgents"
    cat > "$PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key>
  <array><string>$REPO_DIR/run-publisher.sh</string></array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>$REPO_DIR/publisher.log</string>
  <key>StandardErrorPath</key><string>$REPO_DIR/publisher.log</string>
</dict>
</plist>
PLIST
    launchctl unload "$PLIST" >/dev/null 2>&1 || true
    launchctl load "$PLIST"
    say "Loaded $LABEL. Logs: $REPO_DIR/publisher.log"
    note "Stop with:  launchctl unload $PLIST"
  else
    note "Skipped. Load later with: launchctl load $PLIST"
  fi
fi

finish
say "Run modes at a glance:"
note "  nix run .#debug   -- once     # SecretSpec + Python dev mode (dry-run capable)"
note "  nix run .#sandbox -- once     # inside a Microsandbox microVM"
note "  launchctl load $PLIST         # the persistent poll loop"
